import type { Metadata } from "next";
import { Coda } from "next/font/google";
import "./globals.css";

const coda = Coda({
  variable: "--font-coda",
  subsets: ["latin"],
  weight: "400",
});
import { ValueProvider } from "@/hooks/valueContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={coda.variable}>
      <body className="min-h-full flex flex-col">
        <ValueProvider>{children}</ValueProvider>
      </body>
    </html>
  );
}
